### ISSUE TITLE
How do I deploy this?

### ISSUE THREAD

**Issue by WaltDisneyWorld** [Vexcited/createdisbot#1]
How do I deploy this?

**Comment by Vexcited** [comment]
Actually, the project is under development and currently paused... I have some more important projects at the moment, sorry !

If you want to know, the only thing that I've done at the moment is to run a electron app in the /desktop... so yeah not very interesting
The website doesn't even works well (maybe because nothing is really made on it).

When I'll have time, I'll try my best to update this project. I really want to work on this, but atm I have no time. Sorry, try next year maybe ! (i know that's long)

(btw if you want to run the electron app, just run `yarn start` i think in the /desktop directory and it will maybe run (i don't really remember my scripts currently))
